services:
  - type: web
    name: lluvia-de-basura-b2b
    env: docker
    region: ohio
    plan: free # Considerar plan 'starter' para evitar suspensión (cold-starts) en reuniones B2B
    branch: main
    envVars:
      - key: PORT
        value: "5000"
